### ISSUE TITLE
Mappings are global

### ISSUE THREAD

**Issue by benknoble** [b-layer/musecnav#1]
First, kudos for working on what seems like a cool and obviously helpful plugin—I have a feeling it will be much better than custom folds for me.

I had a chance to browse through the code at a structural level (i.e., I ignored the various algorithms for handling popups and building the ToC). While doing so, I noted that the mappings are created globally by a dummy call in ftdetect. I'm curious why that is and if there's a better solution.

Personally, I would prefer `<buffer>` mappings (and this goes all the way to the `<Plug>` level). There are so many ways to do this, and I'm happy to work on PRs for it, but I wanted your input first to design it the way you think will be best.

My personal preference would be buffer-local mappings in `ftplugin/{asciidoc,markdown}.vim` (`ftdetect` just doesn't seem like a good place). To avoid duplication, we could have an autoload function `musecnav#Initialize` that creates the actual mappings. This would also allow us to move a good chunk of initialization code from out of the top-level of the autoload file (feels dirty to me, as it relies on calling order).

The only caveat I see with this approach is that `hasmapto` doesn't work as well:

- If the user puts mappings in `.vim/ftplugin/...`, then the plugin code runs after and all is good
- If the user puts mappings in `.vim/after/ftplugin/...`, the the plugin code runs first and the user has to unmap if they want to

Typical solutions:

- don't provide default mappings; let the user pick those (this is an approach I tend to take, putting out functions and expecting users to create their own commands/mappings)
- provide mappings via a global variable with the original defaults (`<F7>`, etc.); `:execute` is helpful here
- provide default mappings unless a global variable that says not to is true (similar to the first item, but less of a "breaking change")

I'm not sure what a better design looks like, but I'm open to suggestions.

Otherwise, I'm looking forward to trying this out!

**Comment by b-layer** [comment]
Hey @benknoble . Thanks for the feedback. I happen to be totally slammed with things/life right now but will  properly read this (and take a look at your project) in due course...later in the week hopefully. Cheers. -B

**Comment by b-layer** [comment]
@benknoble  If I were writing this from the start for public consumption I definitely wouldn't have mapped keys enabled by default since they will inevitably step on someone's existing mappings (though I'm guessing F7 is rarely used by vimmers). Since it's public now I plan to disable them and, at least in the short term, provide a global config var to enable them (coincidentally, that's how vim-iced does it: `let g:iced_enable_default_key_mappings = 1`). I'll also document how to map the `<Plug>` commands for those who prefer custom keys. Cheers.

**Comment by b-layer** [comment]
I followed the model of a couple other plugins that are filetype specific but NOT filetype plugins (e.g. vim-fireplace). Hotkeys are disabled by default, too, and can be enabled with `let g:musecnav_use_default_keymap = 1`.
